export const LOAD_FILTERS = 'LOAD_FILTERS';
export const CHANGE_STATUS_FILTER = 'CHANGE_STATUS_FILTER';
export const CREATE_UPLOAD_FILTERS = 'CREATE_UPLOAD_FILTERS';
export const UPLOAD_CARDS = 'UPLOAD_BAR';
export const REMOVE_UPLOAD_FILTER = 'REMOVE_UPLOAD_FILTER';
